### ISSUE TITLE
Getting An Expression Array

### ISSUE THREAD

**Issue by hexhead** [rdshankar/RImmPort#4]
Ravi,

I am attempting to get the microarray data from a study SDY269. I am using RImmport, and I really like it so far. I thought it would be under Assay Type: Array.

```
> getListOfAssayTypes()
[1] "ELISA"         "ELISPOT"       "Array"         "PCR"           "HLA Typing"    "MBAA"         
[7] "HAI"           "Neut Ab Titer" "Flow"         

sqlite_conn <- dbConnect(SQLite(), dbname=file.path(db_dir, "ImmPort.sqlite"))
setImmPortDataSource(sqlite_conn)
sdy269.array <- getAssayDataOfStudies("SDY269", "Array")
```

I get a list of two data frames, neither looks like a microarray. 

Thanks in advance,

Bill

**Comment by rdshankar** [comment]
Hi Bill,
For some assays, especially Array and Flow, ImmPort database does not store the raw data, instead it has pointers to the raw data files. Thus, the RImmPort dataframe has a column with file references in it. 
If the data is already in GEO, the column will contain either GSMIDs or file names that contain the GSMIDs. In these cases, you've to download the respective data files from GEO. 
If the data is not in GEO, the column will contain names of raw files at sample level, or reference to one results file for all the samples. In either case, you've to download the files from the ImmPort website.

We will have more automated downloads of study data in future versions of RImmPort.

Thanks,
Ravi

**Comment by hexhead** [comment]
Ravi, do you play sitar? LOL! https://www.youtube.com/watch?v=9sEWBZZWmco

Thanks for the quick reply! I have worked with GEO, so I understand how to
handle those data sets. I am working in the Galaxy environment, though have
also done some work in LabKey. I am trying to pull several expression
matrices across studies.

Thanks again!

Bill

On Wed, Jul 13, 2016 at 5:57 PM, Ravi Shankar notifications@github.com
wrote:

> Hi Bill,
> For some assays, especially Array and Flow, ImmPort database does not
> store the raw data, instead it has pointers to the raw data files. Thus,
> the RImmPort dataframe has a column with file references in it.
> If the data is already in GEO, the column will contain either GSMIDs or
> file names that contain the GSMIDs. In these cases, you've to download the
> respective data files from GEO.
> If the data is not in GEO, the column will contain names of raw files at
> sample level, or reference to one results file for all the samples. In
> either case, you've to download the files from the ImmPort website.
> 
> We will have more automated downloads of study data in future versions of
> RImmPort.
> 
> Thanks,
> Ravi
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rdshankar/RImmPort/issues/4#issuecomment-232510957,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAbg5CVuYlbooIO87aR6-_LkFepkTK9pks5qVW1jgaJpZM4JL1tK
> .

## 

Bill C. White, MS
Research Associate Programmer
University of Tulsa
Tandy School of Computer Science
http://insilico.utulsa.edu/

**Comment by hexhead** [comment]
I am going to close this issue. Thanks!
